name: Azure Login

description: |
  Reusable step template for Azure login using OIDC.

inputs:
  client-id:
    required: true
    type: string
  tenant-id:
    required: true
    type: string
  subscription-id:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.subscription-id }}
        enable-AzPSSession: true
