name: Set Version

description: |
  Reusable step template for setting version information.

outputs:
  release_version:
    description: "The release version"
    value: ${{ steps.set_version.outputs.release_version }}
  image_template_name:
    description: "The image template name"
    value: ${{ steps.set_version.outputs.image_template_name }}

inputs:
  run-output-name:
    required: true
    type: string

runs:
  using: composite
  steps:
    # ── Version = run‑number‑shortSHA ───────────────────────────
    - name: Set version
      id: set_version
      shell: bash
      run: |
        set -euo pipefail
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
        VERSION="${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
        echo "release_version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "image_template_name=${{ inputs.run-output-name }}-${VERSION}" >> "$GITHUB_OUTPUT"
