mode = "git-branch"

[git.tags]
prefix = "v"

[semver]
patch = ["hotfix/", "fix/"]
minor = ["feature/", "release/"]
major = ["release/major-", "breaking/"]

[version_file]
default = ".version"
trigger = ".version-trigger"
