name: Windows Build and Distribution
description: |
  This workflow builds and distributes a custom VM image using the Azure Image Builder service.
  It uses a template to create a shared image gallery image and distribute it across regions.
on:
  push:
    branches: ["main"] # still limit to main
    paths:
      - "templates/1_Creating_a_Custom_Win_Shared_Image_Gallery_Image/**" # any file in that folder
      - ".github/workflows/GoldenWindowsImage.yml" # keep if you really want it
  pull_request: # run on PRs targeting main
    branches: ["main"]
    paths:
      - "templates/1_Creating_a_Custom_Win_Shared_Image_Gallery_Image/**"
  workflow_dispatch: # manual run button

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write

jobs:
  run-image-builder:
    name: Build and distribute custom VM image
    uses: ./.github/workflows/template-modular.yaml
    with:
      templateFolder: "1_Creating_a_Custom_Win_Shared_Image_Gallery_Image" # Folder containing the image template (located in the ./templates directory)
      templateName: "GoldenWindowsImage.json" # JSON template used for creating the custom VM image
      templateType: "armTemplate" # armTemplate or imageTemplate
      sigResourceGroup: "rg-example-westus2-imagebuilder-001" # Azure resource group for the Shared Image Gallery resources
      imageDefName: "GoldenWindowsImage" # Name for the Image Definition in the gallery
      sigName: "appImageGallery" # Name of the Shared Image Gallery
      uaiIdentityName: "rai-identity"
      location: "westus2" # Primary region for building the image
      additionalregion: "eastus2" # Additional region for image replication
      runOutputName: "GoldenWindowsImage" # Identifier used for the build output
      buildRGName: "rg-example-westus2-windows-001" # Resource group for the image build (optional, can be the same as sigResourceGroup)
    secrets: inherit
