name: GoldenLinuxImage Build and Distribution
description: |
  This workflow builds and distributes a custom VM image using the Azure Image Builder service.
  It uses a template to create a shared image gallery image and distribute it across regions.
on:
  push:
    branches: ["main"]
    paths:
      - templates/1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image/GoldenLinuxImage.json
      - .github/workflows/GoldenLinuxImage.yml
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      templateFolder: "1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image" # Folder containing the image template (located in the ./templates directory)
      templateName: "GoldenLinuxImage.json" # JSON template used for creating the custom VM image
      sigResourceGroup: "rg-connectivity-prod-westus2-example-001" # Azure resource group for the Shared Image Gallery resources
      imageDefName: "GoldenLinuxImage" # Name for the Image Definition in the gallery
      sigName: "appImageGallery" # Name of the Shared Image Gallery
      location: "westus2" # Primary region for building the image
      additionalregion: "eastus2" # Additional region for image replication
      runOutputName: "GoldenLinuxImage" # Identifier used for the build output
      buildOS: "linux" # Operating system type for the image
    secrets: inherit
