name: create_custom_vm_image
on:
  workflow_dispatch:
    inputs:
      versionBump:
        required: true
        type: choice
        description: "Version bump type: major, minor, or patch"
        options:
          - major
          - minor
          - patch
  push:
    branches: ["main"] # release branch

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      templateFolder: "1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image"
      templateName: "GoldenImage.json"
      sigResourceGroup: "rg-connectivity-prod-westus2-example-001"
      imageDefName: "GoldenImage"
      sigName: "appImageGallery"
      location: "westus2"
      additionalregion: "eastus2"
      runOutputName: "GoldenImage"
      versionBump: ${{ github.event.inputs.versionBump || 'patch' }}
    secrets: inherit
