name: create_custom_vm_image
on:
  push:
    branches: ["main"] # release branch
  workflow_dispatch: # manual

permissions:
  contents: write
  id-token: write
  actions: read
  security-events: write

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      templateFolder: "1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image"
      templateName: "helloImageTemplateforSIG.json"
      sigResourceGroup: "rg-connectivity-prod-westus2-example-001"
      imageDefName: "GoldenImage"
      sigName: "appImageGallery"
      location: "westus2"
      additionalregion: "eastus2"
      runOutputName: "GoldenImage"
    secrets: inherit
