name: create_custom_vm_image
on:
  workflow_dispatch:
    inputs:
      imageTemplateName:
        required: true
        type: string
        default: "1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image/helloImageTemplateforSIG.json"
      sigResourceGroup:
        required: true
        type: string
        default: "rg-connectivity-prod-westus2-example-001"
      imageDefName:
          required: true
          type: string
          default: "GoldenImage"
      sigName:
          required: true
          type: string
          default: "appImageGallery"
      location:
          required: true
          type: string
          default: "westus2"
      additionalregion:
          required: true
          type: string
          default: "eastus2"
      runOutputName:
          required: true
          type: string
          default: "GoldenImage"

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  call-template:
    uses: ./.github/workflows/template.yaml
    with:
      sigResourceGroup: ${{ github.event.inputs.sigResourceGroup }}
      imageDefName: ${{ github.event.inputs.imageDefName }}
      sigName: ${{ github.event.inputs.sigName }}
      location: ${{ github.event.inputs.location }}
      additionalregion: ${{ github.event.inputs.additionalregion }}
      runOutputName: ${{ github.event.inputs.runOutputName }}
    secrets: inherit
