name: create_custom_vm_image
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-semverbot

      - name: Set VERSION environment variable
        run: echo "VERSION=1.0.0" >> $GITHUB_ENV

      - uses: ./.github/workflows/template.yaml
        with:
          templateFolder: 1_Creating_a_Custom_Linux_Shared_Image_Gallery_Image
          templateName:   helloImageTemplateforSIG.json
          sigResourceGroup: rg-connectivity-prod-westus2-example-001
          imageDefName:     GoldenImage-${{ env.VERSION }}
          sigName:          appImageGallery
          location:         westus2
          additionalregion: eastus2
          runOutputName:    GoldenImage-${{ env.VERSION }}
